### ISSUE TITLE
"load_texture" gui example fails

### ISSUE THREAD

**Issue by mario-bucatini** [defold/examples#12]
It looks like there is a problem with examples/gui/load_texture/load_texture.gui_script in line 30:

	self.texture_url = "https://i.picsum.photos/id/"..math.random(1, 10).."/200/300.jpg"

It seems like the url scheme to fetch a random image from picsum has changed, as this line now fails to retrieve an image?

**Comment by britzl** [comment]
Thanks! I've updated the example to work with the new Picsum API
